In [1]:
import numpy as np

In [595]:
num_classes = 7
true_class = np.random.randint(num_classes)
true_class_prob = np.random.rand()

random_numbers = np.random.rand(num_classes - 1)
remaining_prob = 1 - true_class_prob

false_class_prob = random_numbers / random_numbers.sum() * remaining_prob

prediction_prob = np.insert(false_class_prob, true_class, true_class_prob)
prediction_prob.sum()

1.0

In [597]:
remaining_prob

array([0.05601883, 0.09276686, 0.38756983, 0.01798548, 0.17883035,
       0.26682865])

In [1]:
import torch

In [599]:
torch.tensor([[0.45] * 150] * 64)

tensor([[0.4500, 0.4500, 0.4500,  ..., 0.4500, 0.4500, 0.4500],
        [0.4500, 0.4500, 0.4500,  ..., 0.4500, 0.4500, 0.4500],
        [0.4500, 0.4500, 0.4500,  ..., 0.4500, 0.4500, 0.4500],
        ...,
        [0.4500, 0.4500, 0.4500,  ..., 0.4500, 0.4500, 0.4500],
        [0.4500, 0.4500, 0.4500,  ..., 0.4500, 0.4500, 0.4500],
        [0.4500, 0.4500, 0.4500,  ..., 0.4500, 0.4500, 0.4500]])

In [9]:
test = torch.rand((5, 2, 2))

In [12]:
test

tensor([[[7.5829e-02, 9.9296e-01],
         [3.7113e-03, 7.3160e-01]],

        [[8.2977e-01, 1.5892e-01],
         [1.8631e-01, 9.6026e-01]],

        [[4.5705e-04, 2.4140e-01],
         [1.8949e-01, 8.0281e-01]],

        [[3.1150e-01, 7.2506e-01],
         [4.4518e-01, 8.2035e-01]],

        [[8.1027e-01, 6.3314e-02],
         [7.3156e-02, 9.6462e-01]]])

In [13]:
indices = torch.randperm(5)
test[indices]

In [15]:
indices

tensor([4, 3, 1, 0, 2])

tensor([[[8.1027e-01, 6.3314e-02],
         [7.3156e-02, 9.6462e-01]],

        [[3.1150e-01, 7.2506e-01],
         [4.4518e-01, 8.2035e-01]],

        [[8.2977e-01, 1.5892e-01],
         [1.8631e-01, 9.6026e-01]],

        [[7.5829e-02, 9.9296e-01],
         [3.7113e-03, 7.3160e-01]],

        [[4.5705e-04, 2.4140e-01],
         [1.8949e-01, 8.0281e-01]]])

In [3]:
import torch
from einops.layers.torch import Rearrange
test = torch.rand((32, 150, 6))

In [4]:
re = Rearrange('b (h p1) (w p2) -> b h w (p1 p2)', p1 = 1, p2 = 6)

In [10]:
test[0, 10]

tensor([0.3953, 0.6734, 0.3947, 0.9723, 0.0251, 0.7837])

In [9]:
re(test)[0, 10]

tensor([[0.3953, 0.6734, 0.3947, 0.9723, 0.0251, 0.7837]])

In [1]:
import sys
sys.path.append('../')

In [29]:
model = SimpleViT(6, 64, 1, 4, 256, 10, 150, dim_head = 128, device='cpu')

In [31]:
vsh,lith = model(torch.randn((32, 150, 10)))

torch.Size([32, 150, 65])
